export const listDummyArticle = [
  {
    title: 'Yuk kenalan dengan Coco trinidad',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse lacinia porttitor purus vitae eleifend. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis scelerisque metus odio, ut faucibus nisl viverra eget. Praesent ornare tempus tellus...',
    category: 'Selebriti',
    releaseDate: '2020-08-19',
    view: 145,
    like: 86,
    img:
      'https://cdns.klimg.com/merdeka.com/i/w/news/2020/01/01/1137346/670x335/rahasia-poni-antibadai-lisa-blackpink-tetap-rapi-meskipun-dipakai-dance-heboh.jpg',
    profileImg: 'https://pbs.twimg.com/media/EUz5qgbUYAEKqdF.jpg',
    profileName: 'Lisa Rahayu',
    profileType: 'content writer',
    urlArticle: '/about',
    urlCategory: '/about',
    urlProfile: '/about',
  },
  {
    title: 'Yuk kenalan dengan Coco trinidad',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    category: 'Selebriti',
    releaseDate: '2020-08-19',
    view: 145,
    like: 86,
    img:
      'https://cdns.klimg.com/merdeka.com/i/w/news/2020/01/01/1137346/670x335/rahasia-poni-antibadai-lisa-blackpink-tetap-rapi-meskipun-dipakai-dance-heboh.jpg',
    profileImg: 'https://pbs.twimg.com/media/EUz5qgbUYAEKqdF.jpg',
    profileName: 'Lisa Rahayu',
    profileType: 'content writer',
    urlArticle: '/about',
    urlCategory: '/about',
    urlProfile: '/about',
  },
  {
    title: 'Yuk kenalan dengan Coco trinidad',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    category: 'Selebriti',
    releaseDate: '2020-08-19',
    view: 145,
    like: 86,
    img:
      'https://cdns.klimg.com/merdeka.com/i/w/news/2020/01/01/1137346/670x335/rahasia-poni-antibadai-lisa-blackpink-tetap-rapi-meskipun-dipakai-dance-heboh.jpg',
    profileImg: 'https://pbs.twimg.com/media/EUz5qgbUYAEKqdF.jpg',
    profileName: 'Lisa Rahayu',
    profileType: 'content writer',
    urlArticle: '/about',
    urlCategory: '/about',
    urlProfile: '/about',
  },
];
